version: "3"
services:
  backup:
    container_name: backup
    build:
        context: .
        dockerfile: ./Dockerfile
    image: backup
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Berlin
      - BACKUP_DIRS=ExampleDir_0,ExampleDir_1
      - TARGET_URL=192.168.178.34:873/Backup
    ports:
      - "873:873"
    volumes:
      - /share:/source
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M